#!/bin/bash

# Fetch Pokémon data in parallel
curl -s "https://pokeapi.co/api/v2/pokemon/pikachu" -o pikachu.json &
curl -s "https://pokeapi.co/api/v2/pokemon/charmander" -o charmander.json &
curl -s "https://pokeapi.co/api/v2/pokemon/bulbasaur" -o bulbasaur.json &

# List background jobs
jobs

# Wait for all background jobs to finish
wait

kill $!
